# Generated by Django 4.1.7 on 2023-02-27 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('studio_owner', 'Studio Owner'), ('employee', 'Employee'), ('customer', 'Customer')], default='customer', max_length=20),
        ),
    ]
