# Generated by Django 4.1.7 on 2023-02-27 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studio',
            name='employees',
            field=models.ManyToManyField(related_name='studios_employee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studio',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reservation',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reservation',
            name='studio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.studio'),
        ),
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('studio', 'date', 'time')},
        ),
    ]
