# Generated by Django 4.1.7 on 2023-02-28 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_studioemployee'),
    ]

    operations = [
        migrations.AddField(
            model_name='studio',
            name='max_customers_per_day',
            field=models.IntegerField(default=0),
        ),
    ]
